### ISSUE TITLE
New registration periods from 1st of May

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#475]
This is a subticket to https://github.com/internetee/registry/issues/313

This is the absolute minimum functionality that must go live on 1st of May 2017

* epp support for periods 3m, 6m, 9m, 1y, 2y, 3y, 4y, 5y, 6y, 7y, 8y, 9y, 10y (no schema change is necessary)
* portal for registrars support for the periods 3m, 6m, 9m, 1y, 2y, 3y, 4y, 5y, 6y, 7y, 8y, 9y, 10y
* validation update to set the maximum expire date of any domain to be less than maximum allowed period + 1 year (ie expire_time < max_reg_time + 1 year). This rule is necessary to allow domains to be renewed for another max_reg_time (in this case 10 years) period before the domain is actually expired.
* support on the admin interface to enable adding periods to pricelist for the new and old supported periods (new/renew)
* Remove "log_pricelists"

**Comment by artur-beljajev** [comment]
set default of "days_to_renew_domain_before_expire" to 0

**Comment by artur-beljajev** [comment]
https://meedia.internet.ee/files/Domeenireeglid_01.05.2017.pdf

**Comment by artur-beljajev** [comment]
check permissions!

**Comment by artur-beljajev** [comment]
refactor zones

**Comment by artur-beljajev** [comment]
Remove outdated and unused"rake:zonefile:replace_procedure" rake task (lib/tasks/zonefile.rake)"

**Comment by artur-beljajev** [comment]
Timo:

oluline, et epp ja registripidaja portaali kaudu oleks võimalik registreerida ja pikendada domeene 3 kuust 10 aastani

**Comment by artur-beljajev** [comment]
max_reg_time = 4.years.from_now

**Comment by artur-beljajev** [comment]
EPP:create:

sisuliselt on see +1a ja +1p kell 00.00
ehk kui registreerin preagu domeeni timo.ee, praegu on 25.4.17 16.02
siis valid to väärtus peab olema 26.4.17 00.00
eesti aja järgi

**Comment by artur-beljajev** [comment]
Test directo

**Comment by artur-beljajev** [comment]
```
          hash = {
              "ProductID"      => DOMAIN_TO_PRODUCT[pricelist.zone_name],
              "Unit"           => "tk",
              "ProductName"    => ".#{pricelist.zone_name} registreerimine: #{pricelist.years_amount} aasta",
              "UnitPriceWoVAT" => pricelist.price_decimal/pricelist.years_amount
          }
```

**Comment by artur-beljajev** [comment]
What should system write to "ProductName" and "UnitPriceWoVAT" keys?

**Comment by ratM1n** [comment]
look from example : https://gist.github.com/ratM1n/893ad373907cf489e8495f2890bd52ce

**Comment by artur-beljajev** [comment]
thanks, Martin. I will fix it during next few days.

**Comment by vohmar** [comment]
* delete button does not fit to pricelist view (admin/prices) - needs to be moved back to edit view (admin/prices/_ID_/edit)

**Comment by artur-beljajev** [comment]
https://gist.github.com/ratM1n/893ad373907cf489e8495f2890bd52ce Martin, it is currently only in Estonian. Is it ok to leave it as is?

**Comment by artur-beljajev** [comment]
№ 7: Where do you specify 10 years? According to the log you provided you specified <domain:period unit="0">1</domain:period>.

**Comment by vohmar** [comment]
merget to master, deployment issues to pre-live env (registrar test)

**Comment by vohmar** [comment]
* UI of the registrar portal is broken - looks like an admin interface (header, logo, footer)
* 2 and 3 not fixed

**Comment by artur-beljajev** [comment]
№ 2, 3: Updated
№ 8: Already in master

**Comment by artur-beljajev** [comment]
@ratM1n Please review my question above

**Comment by artur-beljajev** [comment]
Also, the current format is different from the one you sent: "aasta" is hardcoded, so you will never get "aastaT"

**Comment by artur-beljajev** [comment]
Directo spec is needed.

**Comment by artur-beljajev** [comment]
"  every :day, at: '19:00pm' do
    runner 'Directo.send_receipts'
  end if @environment == 'production'"

is this the part responsible for Directo export?
Directo::send_monthly_invoicesseems unused
do you use it manually somehow?
last update was in April 2016 by perfectline

**Comment by artur-beljajev** [comment]
0 0 1 * *       Directo::send_monthly_invoices

**Comment by artur-beljajev** [comment]
Martin:

> "Artut: in sql account_activities.log_pricelist_id refers to what? my first thought was log_pricelists.id but its not, there ara id's which dont exist in log_pricelists table?
> ok, it reffers to prices.id not log_pricelists.id ... confusing!"

**Comment by artur-beljajev** [comment]
- Remove "prices.desc" column

**Comment by artur-beljajev** [comment]
@ratM1n or @teadur Can you please run the following SQL on production:

https://gist.github.com/artur-beljajev/653e6ed359ff36823f205e4da19e3ff1

In test-reg DB there is one account, which refers to non-existing registrar (account 132 refers to registrar 52). I am adding foreign key to "accounts.registrar_id" so it's needed to handle this case before migration's failure.

**Comment by artur-beljajev** [comment]
Also, please make sure all registrars have an account associated. 

https://gist.github.com/artur-beljajev/5d9d284e1a2e22349ddaaa3bf7fa7e9e

**Comment by artur-beljajev** [comment]
Directo is untested. #509 to fix it.

**Comment by teadur** [comment]
@artur-beljajev both queries give 0 results.

**Comment by vohmar** [comment]
We have no delete policy on the registry so there should not be an option to actually delete price list record or zone definition. There must be an option to archive outdated and unused records to help admin interface users.

for price list records the archival option could be solved automatically by hiding any records that have end date in the past.

For zones there needs to be a validation/constraint that makes impossible archiving a zone with at least one active domain registration.

In both cases UI has to offer a filter option to browse through archived objects separately or together with active records (ie. include archived records tick)

**Comment by artur-beljajev** [comment]
@vohmar Do you mind if we still implement those changes in a separate ticket? That way we could release what we currently have. Zone and price management is in admin, so it only affects us.

**Comment by vohmar** [comment]
moved to #313

**Comment by vohmar** [comment]
* domain count is incorrect - there are 30 registrations (17)  and renews (13) for registrara2 @ staging, but current solution returns 19
* UnitPriceWoVAT for periods longer than 1 year mus be devide between years.
eg. for 10 years all rows must have UnitPriceWoVAT="6.00" not UnitPriceWoVAT="60.0"

**Comment by artur-beljajev** [comment]
https://gist.github.com/ratM1n/5717863b39877015bea3870d241b103d
https://gist.github.com/ratM1n/e50f0b2aa08e00c481a7c0263a3cb206

**Comment by artur-beljajev** [comment]
@ratM1n @teadur This ticket deletes "log_pricelists" table. You may want to back-up it.

**Comment by artur-beljajev** [comment]
raise exception if price / period cannot be divided without remainder

**Comment by artur-beljajev** [comment]
Timo:

> ütleks, et startDate selles kontekstis on kuupäev millal esimene aasta jooksma hakkab ja end date see millal viimane periood lõppeb, aga ma väga kindel ei ole hetkel selles
> alguse selgitus on minu jaoks aru saadav

**Comment by vohmar** [comment]
startDate is the date when the second, third etc period will start (ie if I regsiter a domain today for 2 years, the startDate of the second year will be 2018-06-09 and the endDate is the year later accordingly 2019-06-09

**Comment by vohmar** [comment]
merge conflicts with staging

**Comment by artur-beljajev** [comment]
Fixed

**Comment by ratM1n** [comment]
got error on running directo :

irb(main):001:0> Directo.send_monthly_invoices(debug: true)
[DIRECTO] Registrar 1 has nothing to be sent to Directo
[DIRECTO] Registrar 2 has nothing to be sent to Directo
NameError: uninitialized constant Directo::Pricelist
        from /home/registry/registry/releases/133/app/models/directo.rb:169:in `load_activity_pricelist'
        from /home/registry/registry/releases/133/app/models/directo.rb:90:in `block (2 levels) in send_monthly_invoices'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
        from /home/registry/registry/releases/133/app/models/directo.rb:89:in `block in send_monthly_invoices'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `each'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block in find_each'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:50:in `find_each'
        from /home/registry/registry/releases/133/app/models/directo.rb:79:in `send_monthly_invoices'
        from (irb):1
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/registry/registry/releases/133/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'

**Comment by artur-beljajev** [comment]
Is it on staging? Are you running some old version? There is no such method as "load_activity_pricelist". https://github.com/internetee/registry/blob/staging/app/models/directo.rb
(It has been refactored).

**Comment by ratM1n** [comment]
Sry, my bad .. was in old directory .. but now i got this line:

<invoice Number="309904" InvoiceDate="2017-05-31" PaymentTerm="R" CustomerCode="" Language="" Currency="EUR" SalesAgent="SELLER">

for first, CustomerCode="" there should be customer Directo code and secondly PaymentTerm="R" must be "E" not "R" for monthly invoices.

one more minor mistake is in estonian - ".ee registreerimine: 7 aasta" should be ".ee registreerimine: 7 aastat" notice T in end of aastaT, and also kuuD if quantiti is more than 1 for both aasta/kuu.

Numbers are corrrect for total sum and domain quantity.

**Comment by vohmar** [comment]
PaymentTerm R is for test invoices - that is for accountant to differenciate real invoices for test ones in addition to invoice nr. But it is important to make sure that in production E is used instead of R.

Language issues still need attention

**Comment by vohmar** [comment]
in production
