### ISSUE TITLE
Date picker uses US calendar format in portals and admin

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#590]
Date picker in portal and admin dipslays calendar that shows weeks starting with sunday.

![image](https://user-images.githubusercontent.com/7734747/30533136-70cbc8f6-9c60-11e7-905e-8d83d346bdfa.png)

**Comment by artur-beljajev** [comment]
Fixed by #c2f3cb64c7149f6e113aefcef39366898fb30c47.

**Comment by artur-beljajev** [comment]
Fixed for admin, registrar and registrant area.

**Comment by ratM1n** [comment]
deploy fails with error https://gist.github.com/ratM1n/84610ca936670d99be30cb1c8d63c96d

**Comment by teadur** [comment]
My bad didnot notice that the error is already reported, duplicate in #591  comments

**Comment by artur-beljajev** [comment]
Failed because uglifier gem doesn't have non-experimental es6 support. Gem is dropped until decent solution is found/needed.

**Comment by ratM1n** [comment]
still cant deploy, lil different error : https://gist.github.com/ratM1n/c7e6e32ef8240f4acc891b390b55a72c

**Comment by ratM1n** [comment]
had to comment out 
config.assets.js_compressor = :uglifier
from staging.rb and deploy is working now

**Comment by artur-beljajev** [comment]
Cool! Is there anything that prevents to make `staging.rb` the same as config/environments/staging-example.rb? Thay way we could possibly eliminate delay on next deploy, since you don't need to update `staging.rb` until it has differences from production.rb, which ideally it should not.

**Comment by ratM1n** [comment]
current staging.rb has different log level (debug) and changes for outgoing mail handling (our environment specific) .. i dont think its good idea to write this into public example file.

**Comment by vohmar** [comment]
works on staging. Merged to master. Waiting for the deploy and testing on registrars' test env.

**Comment by artur-beljajev** [comment]
thanks for additional info, @vohmar!

**Comment by artur-beljajev** [comment]
@ratM1n 

What if you leave only `log_level`? Mail should be configured on `config/application.yml` instead.

**Comment by ratM1n** [comment]
@artur-beljajev 
OK by me if its possible
